### ISSUE TITLE
Supporting Threading

### ISSUE THREAD

**Issue by phikal** [abbbi/issuelist#8]
Hi,

I used issue2mbox to export the issues from a repository, and imported these into [sourcehut](https://lists.sr.ht/), see [here](https://lists.sr.ht/~pkal/compat-devel). My issue is that every message is presented as a single thread, instead of bundling all messages from an issue into a single thread.  I don't believe this is an issue on sourcehut's end, rather it might be because of the lack of `In-Reply-To`, `References` and `Message-ID` headers.

**Comment by abbbi** [comment]
hm.. in only used mutt for testing and mutt gets the threads right (at least on my system, the issues are shown threaded, even if i cat two mailbox files into one.

The Message-ID header is set for each issue, but for the comments, the comment ID is used, but it shouldnt matter anyway, because this one is to be unique.

I guess the In-Reply-To Header must be added for each comment, containing the Issue-ID.

![bla_000](https://user-images.githubusercontent.com/3919561/155118883-7ecc4739-b06c-4399-94cf-9ebefc4ff86f.jpg)

**Comment by phikal** [comment]
> hm.. in only used mutt for testing and mutt gets the threads right (at least on my system, the issues are shown threaded, even if i cat two mailbox files into one.

This might be because the subject has a Re: at the beginning.

I will try the last commit out to see if it changes anything.

**Comment by phikal** [comment]
It works!
